[Server]
Host = "0.0.0.0"
Port = 1234
BufferSize = 1500 

[Server.DeviceTUN]  
Host = "10.0.0.1"
Route = "10.0.0.0/24"
Platform = "linux"

[Client]
ServerHost = "server"
ServerPort = 1234
BufferSize = 1500  

[Client.DeviceTUN]  
Host = "10.0.0.2"
Route = "10.0.0.0/24"
Platform = "linux"