[Server]
Host = "10.0.0.1"
Port = 1234
BufferSize = 1500

[Server.DeviceTUNAddress]
Host = "10.0.0.1"
Route = "10.0.0.1/24"
Platform = "linux"

[Client]
ServerHost = "10.0.0.1"
ServerPort = 1234
BufferSize = 1500

[Client.DeviceTUNAddress]
Host = "10.0.0.1"
Route = "10.0.0.1/24"
Platform = "linux"