version: '3.8'

services:
  server:
    image: yvv4docker/tunnel-macos
    container_name: server
    hostname: server
    networks:
      - tun-network
    ports:
      - "1234:1234"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./configs/config.toml:/app/configs/config.toml
      - ./configs/encryption/certs/:/app/configs/encryption/certs/
    entrypoint: ./tunnel server --config ./configs/config.toml

  client:
    image: yvv4docker/tunnel-macos
    container_name: client
    hostname: client
    networks:
      - tun-network
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    depends_on:
      - server
    volumes:
      - ./configs/config.toml:/app/configs/config.toml
      - ./configs/encryption/certs/:/app/configs/encryption/certs/
    entrypoint: ./tunnel client --config ./configs/config.toml

networks:
  tun-network:
    driver: bridge