{
 "title": "Send & Receive",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "GO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mem sys bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap alloc bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC last time seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "delta(go_memstats_last_gc_time_seconds[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Direct",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive",
     "type": "timeseries",
     "description": "Receive bytes from client",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(tcp_server_bytes_received_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sent",
     "type": "timeseries",
     "description": "Send bytes via tcp server",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(tcp_server_bytes_sent_total[1m])"
      }
     ]
    }
   ]
  },
  { "title": "Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bytes received from client",
   "type": "timeseries",
   "description": "Total number of bytes received from clients.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(tcp_speedtest_server_bytes_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent to client",
   "type": "timeseries",
   "description": "Total number of bytes sent to clients.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(tcp_speedtest_server_bytes_sent_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}