[Server]
ChannelType = "tcp"

  [Server.TCPConfig]
  Host = "0.0.0.0"
  Port = 1234
  BufferSize = 1500

    [Server.TCPConfig.Encryption]
    Enabled = true
    ServerCert = "./configs/encryption/certs/server.crt"
    ServerKey = "./configs/encryption/certs/server.key"
    CACert = "./configs/encryption/certs/ca.crt"

  [Server.UDPConfig]
  Host = "0.0.0.0"
  Port = 1235
  BufferSize = 1500

    [Server.UDPConfig.Encryption]
    Enabled = true
    ServerCert = "./configs/encryption/certs/server.crt"
    ServerKey = "./configs/encryption/certs/server.key"
    CACert = "./configs/encryption/certs/ca.crt"

  [Server.DeviceTUN]
  Host = "10.0.0.1"
  Route = "10.0.0.0/24"
  Platform = "linux"

[Client]
ChannelType = "tcp"

  [Client.TCPConfig]
  ServerHost = "server"
  ServerPort = 1234
  BufferSize = 1500

    [Client.TCPConfig.Encryption]
    Enabled = true
    ClientCert = "./configs/encryption/certs/client.crt"
    ClientKey = "./configs/encryption/certs/client.key"
    CACert = "./configs/encryption/certs/ca.crt"

  [Client.UDPConfig]
  ServerHost = "server"
  ServerPort = 1235
  BufferSize = 1500

    [Client.UDPConfig.Encryption]
    Enabled = true
    ClientCert = "./configs/encryption/certs/client.crt"
    ClientKey = "./configs/encryption/certs/client.key"
    CACert = "./configs/encryption/certs/ca.crt"

  [Client.DeviceTUN]
  Host = "10.0.0.2"
  Route = "10.0.0.0/24"
  Platform = "linux"